run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - gofmt
    - goimports
    - revive
    - gocyclo
    - dupl

linters-settings:
  gocyclo:
    min-complexity: 15

  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
      - name: var-naming
        severity: warning
        disabled: false
      - name: receiver-naming
        severity: warning
        disabled: false

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude:
    - "error return value not checked.*(Close|Log|Print|Encode)"
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo

output:
  sort-results: true
